/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program;
import data.Data;
import static java.awt.Image.SCALE_DEFAULT;
import java.io.ByteArrayOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author 15142087777的AW
 */
public class ViewDrivingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDrivingJPanel
     */
    private Data data;
    
    public ViewDrivingJPanel(Data data) {
        initComponents();
        displayDriving(data);
    }

    ViewDrivingJPanel(JPanel container, Data data) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createLicenseNumTextField = new javax.swing.JTextField();
        createDateOfIssuedTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        createDateOfExpirationTextField = new javax.swing.JTextField();
        createBloodTypeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewPicturejLabel = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel3.setText("Date of Issued");

        jLabel4.setText("Date of Expiration");

        jLabel5.setText("Blood Type");

        jLabel6.setText("Picture");

        createDateOfExpirationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDateOfExpirationTextFieldActionPerformed(evt);
            }
        });

        createBloodTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBloodTypeTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("View Driving License Information");

        jLabel2.setText("License Number");

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createLicenseNumTextField)
                            .addComponent(createDateOfIssuedTextField)
                            .addComponent(createDateOfExpirationTextField)
                            .addComponent(createBloodTypeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(viewPicturejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(createLicenseNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(createDateOfIssuedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(createDateOfExpirationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(createBloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(viewPicturejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createDateOfExpirationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDateOfExpirationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createDateOfExpirationTextFieldActionPerformed

    private void createBloodTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBloodTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBloodTypeTextFieldActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed
    private void displayDriving(Data data)
    {
        String bloodType = data.getBloodType();
        createBloodTypeTextField.setText(bloodType);
        
        String dateOfExpira = data.getDateOfExpiration();
        createDateOfExpirationTextField.setText(dateOfExpira);
        
        String dateOfIssue = data.getDateOfIssued();
        createDateOfIssuedTextField.setText(dateOfIssue);
        
        String licenseNum = data.getLicenseNum();
        createLicenseNumTextField.setText(licenseNum);
        
        /*显示图片*/
        /*ByteArrayOutputStream picture = data.getPicture();
        createPictureTextField1.setText(picture);*/
        ImageIcon icon = new ImageIcon(data.getPicture());
        icon.setImage(icon.getImage().getScaledInstance(150, 150, SCALE_DEFAULT));
        viewPicturejLabel.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField createBloodTypeTextField;
    private javax.swing.JTextField createDateOfExpirationTextField;
    private javax.swing.JTextField createDateOfIssuedTextField;
    private javax.swing.JTextField createLicenseNumTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel viewPicturejLabel;
    // End of variables declaration//GEN-END:variables
}
