/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1.hospital.patientRole;

import Business.Communal_Customer.Customer;
import Business.Communal_Pet.Pet;
import Business.Communal_PetCase.PetCase;
import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Total_UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import keeptoo.KGradientPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15142087777的AW
 */
public class RegisterJPanel extends keeptoo.KGradientPanel {

    /**
     * Creates new form RegisterJPanel
     */
    KGradientPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    HospitalEnterprise hospitalEnterprise;
    Network network;
    EcoSystem business;
    Customer customer;

    RegisterJPanel(KGradientPanel userProcessContainer, UserAccount account, Organization organization, HospitalEnterprise hospitalEnterprise, Network network, EcoSystem business, Customer customer) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.hospitalEnterprise = hospitalEnterprise;
        this.network = network;
        this.business = business;
        this.customer = customer;
        
        valueLabel.setText(hospitalEnterprise.getName());
        customerNameLabel.setText(customer.getName());
        
        populatePetList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        deseaseNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addPetCaseButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Choose a Pet  to make an Appointment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 460, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Customer Name:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        customerNameLabel.setText("<value>");
        add(customerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 130, -1));

        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PetId", "PetName"
            }
        ));
        jScrollPane1.setViewportView(petTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 170));
        add(deseaseNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 100, -1));

        jLabel2.setText("Disease Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        addPetCaseButton.setText("Add Pet Case");
        addPetCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPetCaseButtonActionPerformed(evt);
            }
        });
        add(addPetCaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 120, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addPetCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPetCaseButtonActionPerformed
        // TODO add your handling code here:
        String deseaseName = deseaseNameTextField.getText();
        
        int selectedRow = petTable.getSelectedRow();
        if(selectedRow<0)
        {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
            populatePetList();
        }
        else
        {
            Pet pet = (Pet)petTable.getValueAt(selectedRow, 0);
            
            PetCase petcase = network.getPetCaseDirectory().createPetCase(deseaseName, pet.getId());
            
            JOptionPane.showMessageDialog(null, "PetCase Add Successfully");
            
            userProcessContainer.remove(this);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }
        
        
    }//GEN-LAST:event_addPetCaseButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPetCaseButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField deseaseNameTextField;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable petTable;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

    private void populatePetList() {
        DefaultTableModel model = (DefaultTableModel) petTable.getModel();
        
        model.setRowCount(0);
        
        for (Pet pet : customer.getPetDirectory().getPetList())
        {
            Object[] row = new Object[2];
            row[0] = pet;
            row[1] = pet.getPetName();
            model.addRow(row);
        }
    }
}
