/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1.hospital.customer;

/**
 *
 * @author 15142087777的AW
 */
public class AppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form hospitalJPanel
     */
    public AppointmentJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pet Hospital Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 67, -1, -1));

        jLabel2.setText("pet id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 147, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 144, 226, -1));

        jLabel3.setText("symptom");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 205, -1, -1));

        jRadioButton1.setText("la du zi");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 201, -1, -1));

        jRadioButton2.setText("cold");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 242, -1, -1));

        jRadioButton3.setText("fever");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 283, -1, -1));

        jRadioButton4.setText("unknown symtom, please make appointment to the vet");
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 324, -1, -1));

        jLabel4.setText("appointment");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 382, -1, -1));

        jRadioButton5.setText("Monday 2-3pm");
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 378, -1, -1));

        jRadioButton6.setText("Sunday 7-8pm");
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 419, -1, -1));

        jButton1.setText("save");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 419, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
