/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1.hospital;

/**
 *
 * @author 15142087777的AW
 */
public class HospitalMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalMainJPanel
     */
    public HospitalMainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Back");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jButton1.setText("Customer");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 190, 40));

        jButton3.setText("Admin");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 190, 40));

        jButton4.setText("Pet Keep");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 190, 40));

        jButton5.setText("Admin");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 190, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
