/*
 * To change this license header, choose License Headers in Project Properties.
 * To chSange this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1.shelter.adoptRole;

import Business.Communal_Customer.Customer;
import Business.Total_UserAccount.UserAccount;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ShelterEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import interface1.hospital.patientRole.RegisterJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import keeptoo.KGradientPanel;

/**
 *
 * @author 15142087777的AW
 */
public class ShelterAdoptJPanel extends keeptoo.KGradientPanel {

    /**
     * Creates new form ShelterAdoptJPanel
     */
    KGradientPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    ShelterEnterprise shelterEnterprise;
    Network network;
    EcoSystem business;

    public ShelterAdoptJPanel(KGradientPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.shelterEnterprise = shelterEnterprise;
        this.network = network;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        int customerId = Integer.parseInt(searchIdTextField.getText());
        
        if(null == network.getCustomerDirectory().searchCustomer(customerId))
        {
            JOptionPane.showMessageDialog(null, "Customer donot exist");
        }
        else
        {
            Customer customer = network.getCustomerDirectory().searchCustomer(customerId);
            
            SelectPetJPanel muajp = new SelectPetJPanel(userProcessContainer, account, organization, shelterEnterprise, network, business, customer);
            userProcessContainer.add("SelectPetJPanel", muajp);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String customerName = addNameTextField.getText();
        
        if(null == addNameTextField.getText())
        {
            JOptionPane.showMessageDialog(null, "Please enter the customer name");
        }
        else
        {
             Customer customer = network.getCustomerDirectory().createCustomer(customerName);
             
            SelectPetJPanel muajp = new SelectPetJPanel(userProcessContainer, account, organization, shelterEnterprise, network, business, customer);
            userProcessContainer.add("SelectPetJPanel", muajp);

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addNameTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchIdTextField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
