/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1.shelter.admin;

/**
 *
 * @author 15142087777的AW
 */
public class AdminFunctionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminFunctionJPanel
     */
    public AdminFunctionJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Admin Function Selection");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jButton2.setText("Pet Manage");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 160, -1));

        jButton3.setText("Supply Manage");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 160, -1));

        jButton4.setText("Pet Manage History");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 160, -1));

        jButton5.setText("Supply Manage History");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 160, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
