/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1.hospital.admin.doctorManage;

import interface1.shelter.admin.petManage.*;

/**
 *
 * @author 15142087777的AW
 */
public class DoctorManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PetManageJPanel
     */
    public DoctorManageJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pet Manage");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        jButton1.setText("Add Pet");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, 40));

        jButton2.setText("Change Pet Repository");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 160, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
